# Generated by Django 3.0.7 on 2020-06-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200625_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
